### ISSUE TITLE
NameError: uninitialized constant RSpec::Matchers::DSL::DefaultImplementations::BuiltIn

### ISSUE THREAD

**Issue by klyonrad** [kirs/rspec-dom-testing#1]
Having the gem breaks for me in the travis setup. I cannot reproduce on my dev machine, but I am creating this issue just in case someone faces a similar issue

```
Caused by:
NameError: uninitialized constant RSpec::Matchers::DSL::DefaultImplementations::BuiltIn
/home/travis/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/active_support.rb:53:in `block in load_missing_constant'
/home/travis/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/active_support.rb:8:in `without_bootsnap_cache'
/home/travis/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/active_support.rb:53:in `rescue in load_missing_constant'
/home/travis/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/active_support.rb:42:in `load_missing_constant'
/home/travis/.rvm/gems/ruby-2.5.3/gems/rspec-expectations-3.8.2/lib/rspec/matchers/dsl.rb:376:in `<module:DefaultImplementations>'
/home/travis/.rvm/gems/ruby-2.5.3/gems/rspec-expectations-3.8.2/lib/rspec/matchers/dsl.rb:375:in `<module:DSL>'
/home/travis/.rvm/gems/ruby-2.5.3/gems/rspec-expectations-3.8.2/lib/rspec/matchers/dsl.rb:4:in `<module:Matchers>'
/home/travis/.rvm/gems/ruby-2.5.3/gems/rspec-expectations-3.8.2/lib/rspec/matchers/dsl.rb:2:in `<module:RSpec>'
/home/travis/.rvm/gems/ruby-2.5.3/gems/rspec-expectations-3.8.2/lib/rspec/matchers/dsl.rb:1:in `<main>'
/home/travis/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
/home/travis/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
/home/travis/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
/home/travis/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
/home/travis/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
/home/travis/.rvm/gems/ruby-2.5.3/gems/rspec-dom-testing-0.1.0/lib/rspec/dom/testing/matchers.rb:1:in `<main>'
```

reproducing (maybe):

```yaml
travis.yml
addons:
  postgresql: 9.6
language: ruby
dist: trusty
rvm:
  - 2.4.5
  - 2.5.3
#  - 2.6.0-preview3
install:
  - bundle install --without development
  - nvm install node
  - node -v
  - npm i -g yarn
  - yarn
env:
  - DB=postgresql
#  - DB=sqlite
before_script:
  - cp config/database.yml.travis config/database.yml
  - sh -c "if [ '$DB' = 'postgresql' ]; then psql -c 'create database database_name' -U postgres; fi"
script:
#  - RAILS_ENV=test bundle exec rails db:schema:load --trace
#  - bundle exec rails db:test:prepare
  - bundle exec rails db:migrate
  - bundle exec rspec
```

```ruby
rails_helper.rb

RSpec.configure do |config|
  config.use_transactional_fixtures = true

  config.infer_spec_type_from_file_location!

  config.filter_rails_from_backtrace!
  config.include RequestSpecHelper, type: :request
  config.include RSpec::Dom::Testing::Matchers
end

```
